kenshoo/react-menu

- README.md
- package.json
- tests/components/dropdown/dropdown.spec.js
> Testing travisCI

- package.json
- semantic_release/analyze_commits.js
Removed custom commit logic.
@liorheber @AmirAsaraf @johanzilber
> Semantic release fix to work as semver

- src/components/dropdown/dropdown.js
- src/components/menu.js
- stories/menu.stories.js
- stories/story_book.scss
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
- tests/components/menu.spec.js
1) Stabilize components
2) Disable active element, because it fails a lot of tests and not working with cascading dropdowns
Fixes #
-
-
-
> Stabilization - tests and disable active eleent

- README.md
> test travis ci - deploy

- package.json
- yarn.lock
> use semantic-release 8.2.0

- README.md
- package.json
- src/components/dropdown/dropdown.js
- src/components/menu.js
- stories/menu.stories.js
- stories/story_book.scss
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
- tests/components/menu.spec.js
- yarn.lock
> Test travis ci

- package.json
> remove pre

- stories/story_book.scss
> feat: initial release

- README.md
- package.json
- src/common/constants.js
- src/components/button/button.js
- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown.scss
- src/components/dropdown/dropdown_icon/dropdown_icon.js
- src/components/dropdown/dropdown_icon/dropdown_icon.scss
- src/index.js
- stories/dropdown.stories.js
- tests/components/button/__snapshots__/button.spec.js.snap
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
- tests/components/dropdown/dropdown_icon/__snapshots__/dropdown_icon.spec.js.snap
- tests/components/dropdown/dropdown_icon/dropdown_icon.spec.js
- Exports DIRECTIONS enum
- Fix: Now overrides component button style in case of outside className is sent
- Add bottom_left direction
- Fix: Now overrides component dropdownIcon style in case of outside className is sent
- Fix: Now overrides component dropdown style in case of outside className is sent
> fix - Export DIRECTIONS and fix buttons styles

- package.json
- Revert version property change
> Change version back to development

- src/components/dropdown/dropdown.js
- src/components/menu.js
- stories/menu.stories.js
- stories/sample_dropdown.js
- stories/sample_item.js
- stories/story_book.scss
- tests/components/__snapshots__/menu.spec.js.snap
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
- tests/components/menu.spec.js
Fixes https://github.com/kenshoo/react-menu/issues/43
-
-
-
> Fix hover behavior and handle open tab

- README.md
- release package with a single root containing all the helper components.
> BREAKING CHANGE: consolidate components to a single entrypoint

- README.md
- config/webpack/loaders.js
- config/webpack/webpack.common.js
- package.json
- yarn.lock
Fixes #
- extract styles to avoid issues with multi menus
>  react-menu | extract the style to an external css

- README.md
- src/components/dropdown/dropdown.js
- tests/components/dropdown/dropdown.spec.js
> fix(menu) Fix exception on menu items clicks

- README.md
@kenshoo/uiinfra 
@yuval-rikover need to bump
> fix(menu): exception on menu items clicks

- src/components/dropdown/dropdown.js
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
Fixes #
@kenshoo/uiinfra 
- isDisabled was not fsupported well for dropdown item
> fix(dropdown): Support isDisabled for dropdown

- README.md
- config/webpack/loaders.js
- config/webpack/webpack.common.js
- package.json
- yarn.lock
@kenshoo/uiinfra 
@liorheber 
Reverting https://github.com/kenshoo/react-menu/pull/55 to fix the usage of the menubar without styling
> BREAKING CHANGE: Revert css extraction

- src/components/menu.js
> fix(dropdown): Outside click for iframes

- README.md
- src/common/constants.js
- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown.scss
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
> Add right_to_top and left_to_top directions

- src/components/dropdown/dropdown_icon/dropdown_icon.js
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
> fix(icon): Support dropdown icon for new directions

- README.md
- src/components/dropdown/dropdown.js
- src/components/dropdown/dropdown_title/dropdown_title.js
- tests/components/dropdown/__snapshots__/dropdown.spec.js.snap
- tests/components/dropdown/dropdown.spec.js
- tests/components/dropdown/dropdown_title/__snapshots__/dropdown_title.spec.js.snap
- tests/components/dropdown/dropdown_title/dropdown_title.spec.js
> fix(withIcon): Dropdown - Add withIcon
